version: '3.7'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mjai_db
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: ./app
    ports:
      - 11600:11600
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - app_data:/log_dir
  # web:
  #   build:
  #     context: ./web
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - app_data:/storage:ro
  #   depends_on:
  #     - db

volumes:
  db_data:
  app_data:
