version: '3.7'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mjai_db
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
  app:
    build:
      context: ./app
    ports:
      - 11600:11600
    depends_on:
      - db
    volumes:
      - ./storage:/log_dir
  web:
    build:
      context: ./web
    ports:
      - 8000:80
    volumes:
      - ./storage:/storage:ro
    depends_on:
      - db
  api:
    image: postgrest/postgrest
    environment:
      - PGRST_DB_URI=postgres://user:password@db:5432/mjai_db
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=user
    depends_on:
      - db
