CREATE TABLE game(
  id SERIAL NOT NULL PRIMARY KEY,
  file_name VARCHAR(255) UNIQUE NOT NULL,
  error_flag BOOLEAN DEFAULT FALSE
);

CREATE TABLE player(
  id SERIAL NOT NULL PRIMARY KEY,
  seat INTEGER NOT NULL,
  game_id INTEGER NOT NULL,
  player_name VARCHAR(255) NOT NULL,
  score INTEGER,
  position INTEGER,
  FOREIGN KEY(game_id) REFERENCES game(id) ON DELETE CASCADE
);

CREATE TABLE kyoku(
  id SERIAL NOT NULL PRIMARY KEY,
  game_id INTEGER NOT NULL,
  bakaze CHAR(1) NOT NULL CHECK(bakaze IN ('E', 'S', 'W')),
  kyoku INTEGER NOT NULL,
  honba INTEGER NOT NULL,
  FOREIGN KEY(game_id) REFERENCES game(id) ON DELETE CASCADE
);

CREATE TABLE hora(
  id SERIAL NOT NULL PRIMARY KEY,
  actor_id INTEGER NOT NULL,
  target_id INTEGER NOT NULL,
  delta INTEGER NOT NULL,
  kyoku_id INTEGER NOT NULL,
  FOREIGN KEY(actor_id) REFERENCES player(id) ON DELETE CASCADE,
  FOREIGN KEY(target_id) REFERENCES player(id) ON DELETE CASCADE,
  FOREIGN KEY(kyoku_id) REFERENCES kyoku(id) ON DELETE CASCADE
);

CREATE TABLE ryukyoku(
  id SERIAL NOT NULL PRIMARY KEY,
  player_id INTEGER NOT NULL,
  tenpai BOOLEAN NOT NULL,
  kyoku_id INTEGER NOT NULL,
  FOREIGN KEY(player_id) REFERENCES player(id) ON DELETE CASCADE,
  FOREIGN KEY(kyoku_id) REFERENCES kyoku(id) ON DELETE CASCADE
);

CREATE TABLE riichi(
  id SERIAL NOT NULL PRIMARY KEY,
  player_id INTEGER NOT NULL,
  kyoku_id INTEGER NOT NULL,
  FOREIGN KEY(player_id) REFERENCES player(id) ON DELETE CASCADE,
  FOREIGN KEY(kyoku_id) REFERENCES kyoku(id) ON DELETE CASCADE
);

CREATE TABLE naki(
  id SERIAL NOT NULL PRIMARY KEY,
  actor_id INTEGER NOT NULL,
  target_id INTEGER NOT NULL,
  kyoku_id INTEGER NOT NULL,
  naki_type CHAR(10) NOT NULL CHECK(naki_type IN ('pon', 'chi', 'daiminkan')),
  FOREIGN KEY(actor_id) REFERENCES player(id) ON DELETE CASCADE,
  FOREIGN KEY(target_id) REFERENCES player(id) ON DELETE CASCADE,
  FOREIGN KEY(kyoku_id) REFERENCES kyoku(id) ON DELETE CASCADE
);
